import { IData } from './type/interfaces';
const petsList: IData[] = [
    {
        name: 'Британский',
        type: 'Кот',
        image: './img/cat-1.jpg',
        itemid: '1',
        itemCount: 4,
        itemYear: 1930,
        itemCountry: 'Англия',
        itemDiff: 'Средне',
        itemPopular: 'Да',
        itemPrice: 600,
    },
    {
        name: 'Саванна',
        type: 'Кот',
        image: './img/cat-2.jpg',
        itemid: '2',
        itemCount: 7,
        itemYear: 1890,
        itemCountry: 'Россия',
        itemDiff: 'Средне',
        itemPopular: 'Нет',
        itemPrice: 5500,
    },
    {
        name: 'Бенгальский',
        type: 'Кот',
        image: './img/cat-3.jpg',
        itemid: '3',
        itemCount: 4,
        itemYear: 1643,
        itemCountry: 'Германия',
        itemDiff: 'Сложно',
        itemPopular: 'Нет',
        itemPrice: 7500,
    },
    {
        name: 'Бирманская',
        type: 'Кот',
        image: './img/cat-4.jpg',
        itemid: '4',
        itemCount: 11,
        itemYear: 1780,
        itemCountry: 'Россия',
        itemDiff: 'Легко',
        itemPopular: 'Нет',
        itemPrice: 4500,
    },
    {
        name: 'Ангорская',
        type: 'Кот',
        image: './img/cat-5.jpg',
        itemid: '5',
        itemCount: 6,
        itemYear: 1921,
        itemCountry: 'Англия',
        itemDiff: 'Сложно',
        itemPopular: 'Нет',
        itemPrice: 12900,
    },
    {
        name: 'Сиамская',
        type: 'Кот',
        image: './img/cat-6.jpg',
        itemid: '6',
        itemCount: 8,
        itemYear: 1650,
        itemCountry: 'Германия',
        itemDiff: 'Сложно',
        itemPopular: 'Да',
        itemPrice: 15500,
    },
    {
        name: 'Абиссинская',
        type: 'Кот',
        image: './img/cat-7.jpg',
        itemid: '7',
        itemCount: 3,
        itemYear: 1780,
        itemCountry: 'Россия',
        itemDiff: 'Средне',
        itemPopular: 'Нет',
        itemPrice: 22500,
    },
    {
        name: 'Бомбейская',
        type: 'Кот',
        image: './img/cat-8.jpg',
        itemid: '8',
        itemCount: 17,
        itemYear: 1850,
        itemCountry: 'Германия',
        itemDiff: 'Легко',
        itemPopular: 'Нет',
        itemPrice: 5500,
    },
    {
        name: 'Сомали',
        type: 'Кот',
        image: './img/cat-9.jpg',
        itemid: '9',
        itemCount: 11,
        itemYear: 1890,
        itemCountry: 'Англия',
        itemDiff: 'Легко',
        itemPopular: 'Да',
        itemPrice: 13500,
    },
    {
        name: 'Лаперм',
        type: 'Кот',
        image: './img/cat-10.jpg',
        itemid: '10',
        itemCount: 7,
        itemYear: 1778,
        itemCountry: 'Россия',
        itemDiff: 'Сложно',
        itemPopular: 'Нет',
        itemPrice: 8500,
    },
    {
        name: 'Хаски',
        type: 'Собака',
        image: './img/dog-2.jpg',
        itemid: '11',
        itemCount: 9,
        itemYear: 1921,
        itemCountry: 'Россия',
        itemDiff: 'Сложно',
        itemPopular: 'Да',
        itemPrice: 23300,
    },
    {
        name: 'Корги',
        type: 'Собака',
        image: './img/dog-1.jpg',
        itemid: '12',
        itemCount: 2,
        itemYear: 1942,
        itemCountry: 'Россия',
        itemDiff: 'Легко',
        itemPopular: 'Да',
        itemPrice: 49000,
    },
    {
        name: 'Бульдог',
        type: 'Собака',
        image: './img/dog-3.jpg',
        itemid: '22',
        itemCount: 21,
        itemYear: 1862,
        itemCountry: 'Англия',
        itemDiff: 'Легко',
        itemPopular: 'Да',
        itemPrice: 29040,
    },
    {
        name: 'Овчарка',
        type: 'Собака',
        image: './img/dog-4.jpg',
        itemid: '14',
        itemCount: 22,
        itemYear: 1931,
        itemCountry: 'Германия',
        itemDiff: 'Легко',
        itemPopular: 'Да',
        itemPrice: 33000,
    },
    {
        name: 'Лабрадор',
        type: 'Собака',
        image: './img/dog-5.jpg',
        itemid: '15',
        itemCount: 12,
        itemYear: 1899,
        itemCountry: 'Германия',
        itemDiff: 'Средне',
        itemPopular: 'Да',
        itemPrice: 49000,
    },
    {
        name: 'Ретривер',
        type: 'Собака',
        image: './img/dog-6.jpg',
        itemid: '16',
        itemCount: 36,
        itemYear: 1882,
        itemCountry: 'Россия',
        itemDiff: 'Средне',
        itemPopular: 'Нет',
        itemPrice: 43000,
    },
    {
        name: 'Пудель',
        type: 'Собака',
        image: './img/dog-7.jpg',
        itemid: '17',
        itemCount: 4,
        itemYear: 1911,
        itemCountry: 'Россия',
        itemDiff: 'Сложно',
        itemPopular: 'Нет',
        itemPrice: 13000,
    },
    {
        name: 'Шпиц',
        type: 'Собака',
        image: './img/dog-8.jpg',
        itemid: '18',
        itemCount: 12,
        itemYear: 1772,
        itemCountry: 'Англия',
        itemDiff: 'Сложно',
        itemPopular: 'Да',
        itemPrice: 17000,
    },
    {
        name: 'Мопс',
        type: 'Собака',
        image: './img/dog-9.jpg',
        itemid: '19',
        itemCount: 7,
        itemYear: 1947,
        itemCountry: 'Германия',
        itemDiff: 'Средне',
        itemPopular: 'Да',
        itemPrice: 14000,
    },
    {
        name: 'Эрдельтерьер',
        type: 'Собака',
        image: './img/dog-10.jpg',
        itemid: '20',
        itemCount: 9,
        itemYear: 1692,
        itemCountry: 'Россия',
        itemDiff: 'Легко',
        itemPopular: 'Нет',
        itemPrice: 49000,
    },
    {
        name: 'Доберман',
        type: 'Собака',
        image: './img/dog-11.jpg',
        itemid: '21',
        itemCount: 5,
        itemYear: 1899,
        itemCountry: 'Россия',
        itemDiff: 'Сложно',
        itemPopular: 'Да',
        itemPrice: 27000,
    },
];

export default petsList;
